window.Q=window.Q||{};
window.Q.english={
t1:[
// be動詞・一般動詞・疑問文・否定文（1学期）50問
{q:"「私は学生です」の英語は？",c:["I am a student.","I is a student.","I are a student.","Me am a student."],a:0,h:"主語がIのbe動詞",e:"主語がIのとき be動詞は am。I am a student.",es:"「私は〜です」と言うとき、Iのあとはかならずamをつけるよ！"},
{q:"「彼は先生です」の英語は？",c:["He is a teacher.","He am a teacher.","He are a teacher.","Him is a teacher."],a:0,h:"主語がheのbe動詞",e:"主語がhe/she/itのとき be動詞は is。",es:"He（彼）・She（彼女）のあとはisをつけるよ！"},
{q:"「あなたたちは友達です」の英語は？",c:["You are friends.","You is friends.","You am friends.","Yours are friends."],a:0,h:"主語がyouのbe動詞",e:"主語がyou/we/theyのとき be動詞は are。",es:"You（あなた）・We（私たち）・They（彼ら）のあとはareをつけるよ！"},
{q:"「私は大阪出身ではありません」の英語は？",c:["I am not from Osaka.","I is not from Osaka.","I are not from Osaka.","I not am from Osaka."],a:0,h:"be動詞の否定はnotを置く",e:"be動詞の否定：be動詞+not。I am not...",es:"「〜ではありません」と言うには、amやisやareのあとにnotをつけるだけだよ！"},
{q:"「あなたは学生ですか？」の英語は？",c:["Are you a student?","You are a student?","Is you a student?","Am you a student?"],a:0,h:"be動詞疑問文：be動詞を主語の前に",e:"be動詞の疑問文：be動詞を主語の前に出す。Are you...?",es:"「〜ですか？」と聞くとき、areやisを文の最初に持ってくるんだよ！"},
{q:"Are you from Osaka? への答えは？（はいの場合）",c:["Yes, I am.","Yes, I is.","Yes, you are.","Yes, am I."],a:0,h:"be動詞の疑問文への答え方",e:"Are you...? への答え：Yes, I am. / No, I am not.",es:"「はい」のときはYes, I am.、「いいえ」のときはNo, I am not.と答えるよ！"},
{q:"Is she a doctor? への答えは？（いいえの場合）",c:["No, she is not.","No, she are not.","No, she am not.","No, is she not."],a:0,h:"she → she is not",e:"No, she is not.(= No, she isn't.)",es:"「いいえ」のときはNoのあとに主語とisを使ってnotをつけるよ！"},
{q:"「私は音楽が好きです」の英語は？",c:["I like music.","I am like music.","I likes music.","I liking music."],a:0,h:"likeは一般動詞",e:"like（好き）は一般動詞。I + like + 目的語。am は不要。",es:"「好き」はlikeという動詞を使うよ！amはいらないんだよ！"},
{q:"「彼女は毎日走ります」の英語は？",c:["She runs every day.","She run every day.","She is run every day.","She running every day."],a:0,h:"三人称単数現在形（3単現）",e:"主語がhe/she/itの一般動詞現在形にはsをつける。run→runs",es:"She（彼女）が主語のとき、動詞の最後にsをつけるよ！run→runsになるよ！"},
{q:"「あなたはテニスをしますか？」の英語は？",c:["Do you play tennis?","Are you play tennis?","Does you play tennis?","You do play tennis?"],a:0,h:"一般動詞の疑問文はDoを使う",e:"一般動詞の疑問文：Do + 主語 + 動詞の原形 + ?",es:"「〜しますか？」と聞くとき、文の最初にDoをつけるよ！"},
{q:"Do you play soccer? への答えは？（はいの場合）",c:["Yes, I do.","Yes, I am.","Yes, I play.","Yes, do I."],a:0,h:"一般動詞疑問文への答え方",e:"Do you...? → Yes, I do. / No, I don't.",es:"Do you〜?と聞かれたら、Yes, I do.かNo, I don't.で答えるよ！"},
{q:"「私はピアノを弾きません」の英語は？",c:["I don't play the piano.","I not play the piano.","I am not play the piano.","I doesn't play the piano."],a:0,h:"一般動詞の否定はdon't",e:"一般動詞の否定：don't（do not）+ 動詞の原形",es:"「〜しません」と言うとき、動詞の前にdon'tをつけるよ！"},
{q:"「本」の英語は？",c:["book","books","back","look"],a:0,h:"読む物",e:"book=本。複数形はbooks。",es:"本はbookだよ！たくさんある場合はbooksになるんだよ！"},
{q:"「学校」の英語は？",c:["school","cool","pool","fool"],a:0,h:"勉強する場所",e:"school=学校",es:"勉強する場所はschool（スクール）だよ！"},
{q:"「猫」の英語は？",c:["cat","car","can","cap"],a:0,h:"にゃーと鳴く動物",e:"cat=猫。複数形はcats。",es:"にゃーと鳴く動物はcat（キャット）だよ！"},
{q:"「食べる」の英語は？",c:["eat","beat","heat","seat"],a:0,h:"ご飯を（　）る",e:"eat=食べる",es:"「食べる」はeat（イート）だよ！ご飯を食べるときに使うよ！"},
{q:"「走る」の英語は？",c:["run","sun","fun","gun"],a:0,h:"足で速く移動する",e:"run=走る",es:"「走る」はrun（ラン）だよ！運動するときに使う言葉だよ！"},
{q:"「見る・見える」の英語は？",c:["see","sea","bee","fee"],a:0,h:"目で（　）る",e:"see=見る・見える",es:"「見る」はsee（スィー）だよ！目でなにかを見るときに使うよ！"},
{q:"「行く」の英語は？",c:["go","do","no","so"],a:0,h:"（　）school",e:"go=行く",es:"「行く」はgo（ゴー）だよ！go to schoolで「学校に行く」だよ！"},
{q:"「勉強する」の英語は？",c:["study","steady","story","sunny"],a:0,h:"学校でする行為",e:"study=勉強する",es:"「勉強する」はstudy（スタディ）だよ！毎日studyしよう！"},
{q:"「大きい」の英語は？",c:["big","pig","fig","dig"],a:0,h:"sizeが（　）",e:"big=大きい",es:"「大きい」はbig（ビッグ）だよ！大きいものを見たときに使うよ！"},
{q:"「速い」の英語は？",c:["fast","last","past","mast"],a:0,h:"usain boltは（　）",e:"fast=速い",es:"「速い」はfast（ファスト）だよ！チーターみたいに速いね！"},
{q:"「I am not」の短縮形は？",c:["I'm not","I amn't","Im not","I'am not"],a:0,h:"I am = I'm",e:"I am = I'm。I'm not が短縮形。",es:"I amをつなげてI'mと書けるよ！「ではない」はI'm notだよ！"},
{q:"「she is」の短縮形は？",c:["she's","shes","she'is","sh's"],a:0,h:"is を 's に短縮",e:"she is = she's",es:"she isをくっつけてshe'sと書けるよ！アポストロフィ（'）を忘れずにね！"},
{q:"「are not」の短縮形は？",c:["aren't","are'nt","arnot","a'ren't"],a:0,h:"aren't",e:"are not = aren't",es:"are notをくっつけてaren'tと書けるよ！notのoが消えるんだよ！"},
{q:"「This is 〜」の否定は？",c:["This is not 〜","This not is 〜","This doesn't 〜","Not this is 〜"],a:0,h:"be動詞の後にnot",e:"This is not 〜（= This isn't 〜）",es:"「これは〜ではない」と言うとき、isのあとにnotをつけるよ！"},
{q:"「Is this your bag?」の答え（はい）は？",c:["Yes, it is.","Yes, this is.","Yes, that is.","Yes, is it."],a:0,h:"thisはitで受ける",e:"「これは」と聞かれたら it で受ける。Yes, it is.",es:"thisで聞かれたら答えのときはitを使うよ！Yes, it is.と答えるんだよ！"},
{q:"「friend」の複数形は？",c:["friends","friend's","friendes","friende"],a:0,h:"sをつける",e:"friend → friends（普通の複数形：sをつける）",es:"「友達がたくさん」のときはfriendにsをつけてfriendsにするよ！"},
{q:"「bus」の複数形は？",c:["buses","buss","bus's","buse"],a:0,h:"語尾がsで終わる→esをつける",e:"s, x, ch, sh で終わる語 → esをつける。bus → buses",es:"busのように最後がsで終わる言葉にはesをつけてbusesにするよ！"},
{q:"「box」の複数形は？",c:["boxes","boxs","box's","boxies"],a:0,h:"語尾がx→es",e:"box → boxes",es:"boxのように最後がxで終わる言葉にはesをつけてboxesにするよ！"},
{q:"「city」の複数形は？",c:["cities","citys","city's","cityes"],a:0,h:"子音+y → yをiに変えてes",e:"子音字+yで終わる語：y→i+es。city→cities",es:"cityのようにyで終わる言葉は、yをiに変えてesをつけてcitiesにするよ！"},
{q:"「I」「my」「me」はそれぞれ何の形？",c:["主格・所有格・目的格","所有格・主格・目的格","目的格・主格・所有格","主格・目的格・所有格"],a:0,h:"I=主語、my=〜の、me=目的語",e:"I（主格：主語）・my（所有格：〜の）・me（目的格：目的語）",es:"Iは「私は」、myは「私の」、meは「私を・私に」という意味だよ！"},
{q:"「彼の」という所有格は？",c:["his","he","him","he's"],a:0,h:"he→his",e:"he（彼は）→ his（彼の）。所有格。",es:"「彼の〜」と言うときはhisを使うよ！his bagで「彼のカバン」だよ！"},
{q:"「彼女の」という所有格は？",c:["her","she","hers","she's"],a:0,h:"she→her",e:"she（彼女は）→ her（彼女の）",es:"「彼女の〜」と言うときはherを使うよ！her bookで「彼女の本」だよ！"},
{q:"「私たちの」は？",c:["our","we","us","ours"],a:0,h:"we→our",e:"we（私たちは）→ our（私たちの）",es:"「私たちの〜」と言うときはourを使うよ！our schoolで「私たちの学校」だよ！"},
{q:"「This is my book.」の下線myを問う疑問文は？",c:["Whose book is this?","What book is this?","Which is this?","Who book is this?"],a:0,h:"「誰の〜？」はWhose",e:"所有格を問うのは whose。Whose book is this?",es:"「誰の〜？」と聞くときはWhoseを使うよ！Whose book is this?で「誰の本？」だよ！"},
{q:"「I play basketball.」をhe主語に変えると？",c:["He plays basketball.","He play basketball.","He is play basketball.","He do play basketball."],a:0,h:"三人称単数現在：sをつける",e:"he/she/itが主語の一般動詞現在形にはsをつける。play→plays",es:"heが主語のときはplayにsをつけてplaysにするよ！"},
{q:"「have」の三人称単数現在形は？",c:["has","haves","have","is have"],a:0,h:"have は不規則変化",e:"have → has（三人称単数現在の特殊な変化）",es:"haveは特別で、he/sheのときはhasに変わるよ！覚えちゃおう！"},
{q:"「Does she play tennis?」の答え（いいえ）は？",c:["No, she doesn't.","No, she don't.","No, she isn't.","No, does she."],a:0,h:"Does → doesn't",e:"Does...? → Yes, she does. / No, she doesn't.",es:"Does〜?と聞かれたら、「いいえ」はNo, she doesn't.と答えるよ！"},
{q:"「what」の意味は？",c:["何","誰","どこ","いつ"],a:0,h:"What is this?",e:"what=何",es:"whatは「何？」という意味だよ！What is this?で「これは何？」だよ！"},
{q:"「who」の意味は？",c:["誰","何","どこ","いつ"],a:0,h:"Who are you?",e:"who=誰",es:"whoは「誰？」という意味だよ！Who are you?で「あなたは誰？」だよ！"},
{q:"「where」の意味は？",c:["どこ","何","誰","いつ"],a:0,h:"Where do you live?",e:"where=どこ",es:"whereは「どこ？」という意味だよ！Where is it?で「それはどこ？」だよ！"},
{q:"「when」の意味は？",c:["いつ","なぜ","何","どこ"],a:0,h:"When is your birthday?",e:"when=いつ",es:"whenは「いつ？」という意味だよ！When is it?で「いつ？」と聞けるよ！"},
{q:"「What do you want?」の答え方は？",c:["I want a new bag.","I am want a bag.","I wanting a bag.","Want I a bag."],a:0,h:"I want 〜で答える",e:"What do you want? → I want 〜.",es:"「何がほしいの？」と聞かれたら、I want 〜.で答えるよ！"},
{q:"「like」を使った文「彼女は犬が好きです」は？",c:["She likes dogs.","She like dogs.","She is like dogs.","She do like dogs."],a:0,h:"she→三人称：likes",e:"主語がshe→ likes。She likes dogs.",es:"sheが主語のとき、likeにsをつけてlikesにするよ！She likes dogs.だよ！"},
{q:"「speak」の意味は？",c:["話す","聞く","歌う","書く"],a:0,h:"speak English",e:"speak=話す",es:"speakは「話す」という意味だよ！speak Englishで「英語を話す」だよ！"},
{q:"「I study English every day.」の否定文は？",c:["I don't study English every day.","I am not study English every day.","I not study English every day.","I doesn't study English every day."],a:0,h:"一般動詞の否定：don't",e:"一般動詞（study）の否定：don't + 動詞の原形",es:"「勉強しません」と言うときはstudyの前にdon'tをつけるよ！"},
{q:"be動詞と一般動詞の違いは？",c:["be動詞は状態、一般動詞は動作","同じもの","be動詞は動作を表す","一般動詞はam/is/areのこと"],a:0,h:"am/is/are vs run/like/play",e:"be動詞（am/is/are）：状態・存在を表す。一般動詞（run/like/eat等）：動作・行為を表す。",es:"am/is/areは「〜です・います」、run/likeは「走る・好き」みたいな動きを表すよ！"},
{q:"「We are in the same class.」の意味は？",c:["私たちは同じクラスです","私たちは同じ場所にいます","私たちは一緒に来ました","私たちは友達です"],a:0,h:"same=同じ、class=クラス",e:"We are in the same class.=私たちは同じクラスです。",es:"sameは「同じ」、classは「クラス」だよ！私たちは同じクラスです、という文だよ！"}
],
t2:[
// 代名詞・複数形・can・疑問詞（2学期）50問
{q:"「私を」（目的格）は？",c:["me","my","I","mine"],a:0,h:"I→me",e:"I（主格）→ me（目的格）→ my（所有格）→ mine（所有代名詞）",es:"「私を」「私に」と言うときはmeを使うよ！Tell me.で「私に教えて」だよ！"},
{q:"「彼を/彼に」（目的格）は？",c:["him","his","he","himself"],a:0,h:"he→him",e:"he（主格）→ him（目的格）",es:"「彼を」「彼に」と言うときはhimを使うよ！I like him.で「私は彼が好き」だよ！"},
{q:"「彼女を/彼女に」（目的格）は？",c:["her","she","hers","herself"],a:0,h:"she→her（目的格と所有格が同じ）",e:"she→ her（目的格・所有格どちらもher）",es:"「彼女を」「彼女の」どちらもherを使うよ！一緒だから覚えやすいね！"},
{q:"「私たちを」（目的格）は？",c:["us","our","we","ours"],a:0,h:"we→us",e:"we（主格）→ us（目的格）",es:"「私たちを」「私たちに」と言うときはusを使うよ！Join us!で「仲間に入って！」だよ！"},
{q:"「彼ら/彼女らの」は？",c:["their","they","them","theirs"],a:0,h:"they→their",e:"they（主格）→ their（所有格）→ them（目的格）",es:"「彼らの」と言うときはtheirを使うよ！their schoolで「彼らの学校」だよ！"},
{q:"「これは私の本です」の英語は？",c:["This is my book.","This is me book.","This is mine book.","This is I book."],a:0,h:"名詞の前には所有格",e:"名詞（book）の前には所有格（my）を使う。",es:"本（book）の前には「私の」を表すmyをつけるよ！meやmineじゃないよ！"},
{q:"「この本は私のものです」の英語は？",c:["This book is mine.","This book is my.","This book is me.","This book is I."],a:0,h:"「私のもの」は所有代名詞mine",e:"所有代名詞：名詞の代わりに使う。mine=私のもの",es:"「私のもの」と言うときはmineを使うよ！This book is mine.で「この本は私のものです」だよ！"},
{q:"「彼女のもの」という所有代名詞は？",c:["hers","her","she","herself"],a:0,h:"her→hers",e:"hers=彼女のもの（所有代名詞）",es:"「彼女のもの」はhersだよ！herにsをつけるだけで覚えやすいよ！"},
{q:"「〜することができる」という意味の助動詞は？",c:["can","do","be","will"],a:0,h:"can swim=泳ぐことができる",e:"can＋動詞の原形：〜することができる",es:"canは「〜できる」という意味だよ！I can swim.で「私は泳げる」だよ！"},
{q:"「私は速く走れます」の英語は？",c:["I can run fast.","I can runs fast.","I am can run fast.","I running fast."],a:0,h:"can+動詞の原形",e:"can の後は動詞の原形。I can run fast.",es:"canのあとは動詞をそのままの形で使うよ！I can run fast.で「速く走れる」だよ！"},
{q:"「彼女は中国語を話せますか？」の英語は？",c:["Can she speak Chinese?","Does she can speak Chinese?","She can speaks Chinese?","Is she can speak Chinese?"],a:0,h:"Can+主語+動詞の原形?",e:"can の疑問文：Can + 主語 + 動詞の原形?",es:"「〜できますか？」と聞くときはCanを文の最初に持ってくるよ！"},
{q:"Can you swim? への答え（はい）は？",c:["Yes, I can.","Yes, I do.","Yes, I am.","Yes, can I."],a:0,h:"can → can",e:"Can you...? → Yes, I can. / No, I can't.",es:"Can you〜?と聞かれたら、「はい」はYes, I can.と答えるよ！"},
{q:"「私は泳げません」の英語は？",c:["I can't swim.","I not can swim.","I am can't swim.","I don't can swim."],a:0,h:"can't = cannot",e:"can の否定：can't（cannot）+ 動詞の原形",es:"「〜できない」はcan'tを使うよ！I can't swim.で「泳げない」だよ！"},
{q:"「〜してもいいですか？」と許可を求めるとき使う助動詞は？",c:["Can","Do","Be","Have"],a:0,h:"Can I〜?",e:"Can I + 動詞の原形?：〜してもいいですか？（許可を求める）",es:"「〜してもいい？」と聞くときはCan I〜?を使うよ！Can I go?で「行っていい？」だよ！"},
{q:"「何時ですか？」の英語は？",c:["What time is it?","What is time?","How time is it?","Which time is it?"],a:0,h:"What time〜?",e:"「何時？」はWhat time is it?",es:"時間を聞くときはWhat time is it?だよ！「今何時？」って聞くときに使うよ！"},
{q:"「なぜ」を表す疑問詞は？",c:["Why","What","Where","When"],a:0,h:"理由を聞く",e:"why=なぜ。Why do you like it?",es:"「なんで？」「どうして？」と聞くときはWhyを使うよ！"},
{q:"「どのように・どんな様子で」を表す疑問詞は？",c:["How","What","Where","Which"],a:0,h:"How are you?",e:"how=どのように・どんな",e:"how=どのように・どんな",es:"「どうやって？」「どんな感じ？」と聞くときはHowを使うよ！"},
{q:"「どちら・どれ」を表す疑問詞は？",c:["Which","What","Who","Whose"],a:0,h:"選択肢から選ぶとき",e:"which=どちら（選択肢がある場合）",es:"2つ以上から「どれ？どっち？」と聞くときはWhichを使うよ！"},
{q:"「How many〜?」の意味は？",c:["いくつ？（数）","いくら？（値段）","どのくらい？（量）","どれくらい？（距離）"],a:0,h:"可算名詞の数を聞く",e:"How many + 複数名詞 + ?：（可算名詞の）数を聞く",es:"「いくつ？何個？」と数を聞くときはHow many〜?を使うよ！"},
{q:"「How much is this?」の意味は？",c:["これはいくらですか？","これは何個ですか？","これは何ですか？","これは誰のですか？"],a:0,h:"値段・量を聞く",e:"How much is this?=これはいくらですか？",es:"お店で「これいくら？」と聞くときはHow much is this?だよ！"},
{q:"「What time do you get up?」の意味は？",c:["何時に起きますか？","いつ起きますか？","どこで起きますか？","なぜ起きますか？"],a:0,h:"what time=何時",e:"What time do you get up?=何時に起きますか？",es:"「何時に起きるの？」と聞く文だよ！get upは「起きる」という意味だよ！"},
{q:"「Where do you live?」の答え方は？",c:["I live in Osaka.","I am in Osaka.","I living in Osaka.","I do in Osaka."],a:0,h:"I live in 〜",e:"Where do you live?→I live in Osaka. live in + 場所",es:"「どこに住んでいるの？」と聞かれたら、I live in 〜.で場所を答えるよ！"},
{q:"「Why do you like cats?」への答えは？",c:["Because they are cute.","Because is cute.","They cute because.","I because like cats."],a:0,h:"Becauseで始める",e:"Why〜?への答えはBecause + 理由。",es:"「なんで好きなの？」と聞かれたら、Becauseで始めて理由を言うよ！"},
{q:"「How do you come to school?」の意味は？",c:["どうやって学校に来ますか？","なぜ学校に来ますか？","いつ学校に来ますか？","どこから学校に来ますか？"],a:0,h:"how=どのようにして",e:"How do you come to school?=どうやって通学しますか？",es:"「どうやって学校に来るの？」って通学方法を聞いているよ！"},
{q:"「I come to school by bike.」の意味は？",c:["私は自転車で学校に来ます","私はバイクで来ます","私は学校の近くに住んでいます","私は自転車が好きです"],a:0,h:"by bike=自転車で",e:"by + 交通手段。by bike=自転車で",es:"by bikeは「自転車で」という意味だよ！by busは「バスで」だよ！"},
{q:"「How many students are in your class?」の答えは？",c:["There are 35 students.","I have 35 students.","We are 35.","35 students do."],a:0,h:"There are 〜で答える",e:"How many...?→There are + 数 + 複数名詞.",es:"「何人いるの？」と聞かれたら、There are 〜.で人数を答えるよ！"},
{q:"「Which do you like, cats or dogs?」の意味は？",c:["猫と犬、どちらが好きですか？","猫か犬を好きですか？","猫と犬を教えてください","どちらの犬が好きですか？"],a:0,h:"AorBで選択",e:"Which do you like, A or B?=AとBどちらが好きですか？",es:"2つから「どっちが好き？」と選ばせるときにWhichを使うよ！"},
{q:"「Whose pen is this?」の意味は？",c:["これは誰のペンですか？","これは何のペンですか？","あなたはペンを持っていますか？","どのペンですか？"],a:0,h:"whose=誰の",e:"Whose + 名詞 + is/are 〜?=〜は誰の…ですか？",es:"Whoseは「誰の？」という意味だよ！誰のものか聞くときに使うよ！"},
{q:"「child」の複数形は？",c:["children","childs","childes","child's"],a:0,h:"不規則変化",e:"child → children（不規則複数形）",es:"childは特別な変化をするよ！たくさんの子どもはchildrenになるんだよ！"},
{q:"「man」の複数形は？",c:["men","mans","manes","man's"],a:0,h:"不規則変化",e:"man → men（不規則）",es:"manも特別な変化をするよ！たくさんの男の人はmenになるよ！"},
{q:"「foot」の複数形は？",c:["feet","foots","feets","foot's"],a:0,h:"不規則変化",e:"foot → feet（不規則）",es:"足（foot）も特別な変化をするよ！両足はfeetになるんだよ！"},
{q:"「tooth」の複数形は？",c:["teeth","tooths","teeths","tooth's"],a:0,h:"不規則変化",e:"tooth → teeth（不規則）",es:"歯（tooth）も特別な変化をするよ！たくさんの歯はteethになるよ！"},
{q:"「fish」の複数形は？",c:["fish","fishs","fishes","fishies"],a:0,h:"単複同形",e:"fish → fish（単複同形。fishesも使われることがある）",es:"魚（fish）は1匹でも100匹でもfishのまま変わらないんだよ！"},
{q:"「Can I use your phone?」の意味は？",c:["あなたの電話を使ってもいいですか？","あなたの電話を使えますか？","あなたの電話を使います","電話を使わないでください"],a:0,h:"Can I〜?=〜してもいいですか？",e:"Can I use...?=〜を使ってもいいですか？（許可を求める）",es:"「〜使っていい？」と許可を求めるときはCan I use〜?だよ！"},
{q:"「Please open the window.」の意味は？",c:["窓を開けてください","窓を閉めてください","窓がありますか？","窓を開けましょう"],a:0,h:"Please + 動詞の原形 = 〜してください",e:"Please + 動詞の原形：丁寧な命令・依頼",es:"Pleaseをつけると「〜してください」ってやさしくお願いできるよ！"},
{q:"「Don't run in the classroom.」の意味は？",c:["教室で走らないでください","教室で走ってください","教室に走って来てください","走らないと教室に入れません"],a:0,h:"Don't + 動詞の原形 = 〜するな",e:"Don't + 動詞の原形：否定の命令文",es:"Don't〜!は「〜しちゃダメ！」という意味だよ！教室では走らないでね！"},
{q:"「Let's play soccer!」の意味は？",c:["サッカーをしましょう！","サッカーをしてください","サッカーができますか？","サッカーが好きですか？"],a:0,h:"Let's〜=〜しましょう",e:"Let's + 動詞の原形：〜しましょう（勧誘）",es:"Let's〜!は「〜しようよ！」という意味だよ！友達を誘うときに使うよ！"},
{q:"「What subject do you like?」の答えは？",c:["I like math.","I am like math.","My like is math.","I liking math."],a:0,h:"I like 〜で答える",e:"I like math.（subject=教科）",es:"好きな教科を答えるときはI like 〜.を使うよ！mathは「算数」だよ！"},
{q:"「How about you?」の意味は？",c:["あなたはどうですか？","あなたはどこですか？","あなたは何ですか？","あなたはいつですか？"],a:0,h:"話題を相手に振るとき",e:"How about you?=あなたはどうですか？",es:"自分のことを言ったあとに「あなたは？」って聞くときに使うよ！"},
{q:"「I want to be a teacher.」の意味は？",c:["私は先生になりたいです","私は先生が好きです","私は先生です","私は先生に会いたいです"],a:0,h:"want to be=〜になりたい",e:"want to + 動詞の原形：〜したい。be a teacher=先生になる",es:"「〜になりたい！」はI want to be 〜.で言えるよ！将来の夢を話すときに使おう！"},
{q:"「look」の意味は？",c:["見る・〜に見える","聞く","話す","書く"],a:0,h:"look at me",e:"look=見る。look + 形容詞=〜に見える",es:"lookは「見る」という意味だよ！You look happy!で「うれしそうだね！」だよ！"},
{q:"「come」と「go」の違いは？",c:["comeは話し手側へ、goは話し手から離れる方向","同じ意味","goの方が丁寧","comeはformalでgoはinformal"],a:0,h:"方向が逆",e:"come=（話し手のいる場所へ）来る。go=（話し手から離れて）行く。",es:"comeは「こっちに来て」、goは「向こうに行く」というちがいがあるよ！"},
{q:"「I get up at six.」の意味は？",c:["私は6時に起きます","私は6時に寝ます","私は6時に学校に行きます","私は6時が好きです"],a:0,h:"get up=起きる",e:"get up=起きる。I get up at six.=私は6時に起きます。",es:"get upは「起きる」という意味だよ！毎朝何時に起きているかな？"},
{q:"「I go to bed at ten.」の意味は？",c:["私は10時に寝ます","私は10時に起きます","私は10時にベッドを買います","私は10時に帰ります"],a:0,h:"go to bed=寝る",e:"go to bed=就寝する。I go to bed at ten.=私は10時に寝ます。",es:"go to bedは「寝る」という意味だよ！夜10時に寝る文だよ！"},
{q:"「How long does it take?」の意味は？",c:["どのくらい時間がかかりますか？","どのくらい大きいですか？","どのくらい遠いですか？","いつ着きますか？"],a:0,h:"How long=どのくらいの長さ・時間",e:"How long does it take?=（時間が）どのくらいかかりますか？",es:"「どのくらい時間がかかるの？」と聞くときに使う文だよ！"},
{q:"「It takes about 30 minutes.」の意味は？",c:["約30分かかります","約30分後に着きます","30分間休みます","30分待ちます"],a:0,h:"take=（時間が）かかる",e:"It takes + 時間：〜時間かかる",es:"「約30分かかるよ」という意味だよ！aboutは「約・だいたい」という意味だよ！"},
{q:"「I have two cats.」を疑問文にすると？",c:["How many cats do you have?","How much cats do you have?","What cats do you have?","How many cat do you have?"],a:0,h:"数を聞くのはHow many+複数名詞",e:"How many + 複数名詞 + do you have?",es:"「何匹持っているの？」と数を聞くときはHow many cats do you have?だよ！"},
{q:"「Can you help me?」の意味は？",c:["手伝ってもらえますか？","私を助けることができますか？","あなたは私を助けますか？","私は助けが必要です"],a:0,h:"Can you〜?=〜してもらえますか？（依頼）",e:"Can you + 動詞の原形?：〜してもらえますか？",es:"「手伝ってくれる？」と頼むときにCan you help me?って言うよ！"},
{q:"「I can't speak French.」の意味は？",c:["私はフランス語が話せません","私はフランスが好きではありません","私はフランス語を勉強しません","私はフランスに行きません"],a:0,h:"can't=できない",e:"can't speak French=フランス語を話すことができない",es:"can'tは「〜できない」だよ！フランス語が話せないという文だよ！"},
{q:"「What are you doing?」の意味は？",c:["あなたは何をしていますか？","あなたは何をしますか？","あなたは何をしましたか？","あなたは何になりますか？"],a:0,h:"進行形の疑問文",e:"What are you doing?=今何をしていますか？（現在進行形）",es:"「今何してるの？」って聞くときに使う文だよ！今まさにしていることを聞くよ！"}
],
t3:[
// 3人称単数現在・現在進行形・過去形（3学期）50問
{q:"「彼は毎日英語を勉強します」の英語は？",c:["He studies English every day.","He study English every day.","He is study English every day.","He studys English every day."],a:0,h:"study→studiesに変化",e:"study（子音+y）→ studies（y→i+es）。He studies...",es:"studyはheが主語のとき、yをiに変えてesをつけてstudiesになるよ！"},
{q:"「watch」の三人称単数現在形は？",c:["watches","watchs","watch","watchies"],a:0,h:"語尾がchで終わる",e:"ch,sh,s,x,o で終わる動詞 → es をつける。watch → watches",es:"watchはchで終わるからesをつけてwatchesになるよ！"},
{q:"「go」の三人称単数現在形は？",c:["goes","gos","go's","goies"],a:0,h:"語尾がoで終わる",e:"go → goes（o で終わる語もesをつける）",es:"goはoで終わるからesをつけてgoesになるよ！"},
{q:"「Does he like cats?」の答え（はい）は？",c:["Yes, he does.","Yes, he do.","Yes, he is.","Yes, does he."],a:0,h:"Does→does",e:"Does...? → Yes, he does. / No, he doesn't.",es:"Does he〜?と聞かれたら、「はい」はYes, he does.と答えるよ！"},
{q:"「She doesn't play soccer.」の意味は？",c:["彼女はサッカーをしません","彼女はサッカーをします","彼女はサッカーができません","彼女はサッカーが嫌いです"],a:0,h:"doesn't=does not",e:"doesn't + 動詞の原形：三人称単数の否定。She doesn't play soccer.",es:"doesn'tは「〜しない」という意味だよ！彼女がサッカーをしない文だよ！"},
{q:"「今走っています」の英語は？（Iで）",c:["I am running now.","I running now.","I run now.","I am run now."],a:0,h:"be動詞+動詞ing",e:"現在進行形：be動詞 + 動詞ing。I am running now.",es:"「今〜しているよ」と言うときはam/is/areのあとに動詞ingをつけるよ！"},
{q:"「run」のing形は？",c:["running","runing","runs","runned"],a:0,h:"子音字を重ねてingをつける",e:"run（短母音+子音で終わる語）→ 子音を重ねてing。running",es:"runはnを2つ重ねてrunningになるよ！最後の文字を重ねるよ！"},
{q:"「swim」のing形は？",c:["swimming","swiming","swims","swimmed"],a:0,h:"子音を重ねてing",e:"swim → swimming（子音字を重ねる）",es:"swimもmを2つ重ねてswimmingになるよ！"},
{q:"「make」のing形は？",c:["making","makeing","maked","makes"],a:0,h:"語尾のeを取ってing",e:"make（語尾がe）→ eを取ってing。making",es:"makeはeで終わるから、eを取ってingをつけてmakingになるよ！"},
{q:"「write」のing形は？",c:["writing","writeing","wrote","writes"],a:0,h:"語尾のeを取ってing",e:"write → eを取ってing → writing",es:"writeもeを取ってwritingになるよ！eを取ってからingをつけるよ！"},
{q:"「She is reading a book.」の意味は？",c:["彼女は本を読んでいます","彼女は本を読みます","彼女は本を読みました","彼女は本が好きです"],a:0,h:"is reading=読んでいる",e:"is + reading（現在進行形）=〜しているところ",es:"is readingは「読んでいるところ」という意味だよ！今まさに読んでいるよ！"},
{q:"「Are you watching TV?」への答え（はい）は？",c:["Yes, I am.","Yes, I do.","Yes, I watch.","Yes, am I."],a:0,h:"be動詞の疑問文→be動詞で答える",e:"Are you...ing? → Yes, I am. / No, I'm not.",es:"Are you〜ing?と聞かれたら、「はい」はYes, I am.と答えるよ！"},
{q:"「過去形」を表す-(e)dをつけるルールで「play」の過去形は？",c:["played","plaied","plaid","plays"],a:0,h:"そのままedをつける",e:"play（語尾が母音+y）→ played（そのままed）",es:"playはそのままedをつけてplayedになるよ！昨日したことを話すときに使うよ！"},
{q:"「study」の過去形は？",c:["studied","studyed","studid","studies"],a:0,h:"子音+y → yをiに変えてed",e:"study（子音+y）→ y→iにして+ed → studied",es:"studyはyをiに変えてedをつけてstudiedになるよ！"},
{q:"「stop」の過去形は？",c:["stopped","stoped","stops","stop"],a:0,h:"子音を重ねてed",e:"stop（短母音+子音）→子音を重ねてed → stopped",es:"stopはpを2つ重ねてstoppedになるよ！最後の文字を重ねてからedをつけるよ！"},
{q:"「live」の過去形は？",c:["lived","liveed","lives","livd"],a:0,h:"語尾がeで終わる→dだけつける",e:"live（eで終わる）→ dだけつけてed省略 → lived",es:"liveはeで終わるから、dだけつけてlivedになるよ！"},
{q:"「go」の過去形は？（不規則変化）",c:["went","goed","go","gone"],a:0,h:"完全に変化する不規則動詞",e:"go → went（不規則変化）",es:"goは特別な変化をするよ！過去形はwentになるんだよ！"},
{q:"「come」の過去形は？",c:["came","comed","come","commed"],a:0,h:"不規則変化",e:"come → came（不規則）",es:"comeも特別な変化をするよ！過去形はcameになるんだよ！"},
{q:"「eat」の過去形は？",c:["ate","eated","eat","eaten"],a:0,h:"不規則変化",e:"eat → ate（不規則）",es:"eatも特別な変化をするよ！昨日食べたことを言うときはateを使うよ！"},
{q:"「see」の過去形は？",c:["saw","seed","see","seen"],a:0,h:"不規則変化",e:"see → saw（不規則）",es:"seeも特別な変化をするよ！昨日見たことを言うときはsawを使うよ！"},
{q:"「have」の過去形は？",c:["had","haved","have","has"],a:0,h:"不規則変化",e:"have → had（不規則）",es:"haveも特別な変化をするよ！昨日持っていたことを言うときはhadを使うよ！"},
{q:"「get」の過去形は？",c:["got","getted","get","getten"],a:0,h:"不規則変化",e:"get → got（不規則）",es:"getも特別な変化をするよ！過去形はgotになるんだよ！"},
{q:"「make」の過去形は？",c:["made","maked","make","maken"],a:0,h:"不規則変化",e:"make → made（不規則）",es:"makeも特別な変化をするよ！作ったことを言うときはmadeを使うよ！"},
{q:"「take」の過去形は？",c:["took","taked","take","token"],a:0,h:"不規則変化",e:"take → took（不規則）",es:"takeも特別な変化をするよ！過去形はtookになるんだよ！"},
{q:"「I played soccer yesterday.」の意味は？",c:["私は昨日サッカーをしました","私は昨日サッカーをします","私は今サッカーをしています","私はサッカーが好きです"],a:0,h:"played=過去形、yesterday=昨日",e:"played=playの過去形。yesterday=昨日。→昨日サッカーをした。",es:"playedはplayの過去形だよ！yesterdayは「昨日」という意味だよ！"},
{q:"「She went to Tokyo.」の意味は？",c:["彼女は東京へ行きました","彼女は東京へ行きます","彼女は東京にいます","彼女は東京へ行っています"],a:0,h:"went=goの過去形",e:"went=go（行く）の過去形。She went to Tokyo.=彼女は東京へ行きました。",es:"wentはgoの過去形だよ！彼女が東京に行ったことを表しているよ！"},
{q:"「Did you watch TV last night?」の意味は？",c:["あなたは昨晩テレビを見ましたか？","あなたは毎晩テレビを見ますか？","あなたは今テレビを見ていますか？","あなたはテレビが好きですか？"],a:0,h:"Did=過去の疑問文、last night=昨晩",e:"Did + 主語 + 動詞の原形? = 〜しましたか？",es:"過去のことを「〜しましたか？」と聞くときはDidを文の最初に置くよ！"},
{q:"Did she eat breakfast? への答え（いいえ）は？",c:["No, she didn't.","No, she don't.","No, she wasn't.","No, did she."],a:0,h:"Did→didn't",e:"Did...? → Yes, she did. / No, she didn't.",es:"Did〜?と聞かれて「いいえ」のときはNo, she didn't.と答えるよ！"},
{q:"「I didn't do my homework.」の意味は？",c:["私は宿題をしませんでした","私は宿題をします","私は宿題をしています","私は宿題がありません"],a:0,h:"didn't=did not",e:"didn't + 動詞の原形：過去の否定。宿題をしなかった。",es:"didn'tは「〜しなかった」という意味だよ！宿題をやらなかった文だよ！"},
{q:"「Where did you go?」の答えは？",c:["I went to the park.","I go to the park.","I am going to the park.","I gone to the park."],a:0,h:"過去形→過去形で答える",e:"Did/Where did you...? → I + 過去形で答える。",es:"「どこに行ったの？」と聞かれたら、過去形のwentを使って答えるよ！"},
{q:"「last week」の意味は？",c:["先週","来週","今週","毎週"],a:0,h:"last=過去のある時",e:"last week=先週。last night=昨晩。last year=去年。",es:"lastは「この前の」という意味だよ！last weekは「先週」だよ！"},
{q:"「yesterday」の意味は？",c:["昨日","明日","今日","明後日"],a:0,h:"today・tomorrow・yesterday",e:"yesterday=昨日。today=今日。tomorrow=明日。",es:"yesterdayは「昨日」だよ！today（今日）・tomorrow（明日）と一緒に覚えよう！"},
{q:"「ago」の意味は？",c:["〜前","〜後","〜間","〜以来"],a:0,h:"two days ago=2日前",e:"two days ago=2日前。three years ago=3年前。",es:"agoは「〜前」という意味だよ！two days agoは「2日前」だよ！"},
{q:"「He was a student.」の意味は？",c:["彼は生徒でした","彼は生徒です","彼は生徒になります","彼は生徒になりたい"],a:0,h:"was=isの過去形",e:"was=is/amの過去形。過去の状態を表す。",es:"wasはisやamの過去形だよ！昔のことを言うときに使うんだよ！"},
{q:"「They were in Osaka.」の意味は？",c:["彼らは大阪にいました","彼らは大阪にいます","彼らは大阪に行きます","彼らは大阪が好きです"],a:0,h:"were=areの過去形",e:"were=areの過去形。They were in Osaka.=彼らは大阪にいました。",es:"wereはareの過去形だよ！昔大阪にいたことを表しているよ！"},
{q:"「Was she at home?」への答え（はい）は？",c:["Yes, she was.","Yes, she were.","Yes, she is.","Yes, was she."],a:0,h:"be動詞過去形の疑問文",e:"Was/Were...? → Yes, 〜 was/were. / No, 〜 wasn't/weren't.",es:"Was she〜?と聞かれたら、「はい」はYes, she was.と答えるよ！"},
{q:"「I was not tired.」の短縮形は？",c:["I wasn't tired.","I weren't tired.","I amn't tired.","I'm not tired."],a:0,h:"was not = wasn't",e:"was not = wasn't。were not = weren't。",es:"was notをくっつけてwasn'tと書けるよ！「疲れていなかった」という意味だよ！"},
{q:"「He read a book.」のreadは何形？",c:["過去形（同じつづり）","現在形","進行形","完了形"],a:0,h:"read-read-read（不規則）",e:"read（読む）は過去形も read。発音だけ変わる（リード→レッド）。",es:"readは見た目は同じだけど、過去形のときは「レッド」と読むよ！"},
{q:"「I know her.」の意味は？",c:["私は彼女を知っています","私は彼女が好きです","私は彼女に会いました","私は彼女に話しました"],a:0,h:"know=知っている",e:"know=知っている。「知っている」状態なので進行形にしない。",es:"knowは「知っている」という意味だよ！状態を表すから〜ingにはしないよ！"},
{q:"「What did you do last Sunday?」の意味は？",c:["先週の日曜日に何をしましたか？","今日の日曜日に何をしますか？","毎週日曜日に何をしますか？","日曜日に何をしていますか？"],a:0,h:"did=過去、last Sunday=先週の日曜日",e:"What did you do last Sunday?=先週の日曜日に何をしましたか？",es:"「先週の日曜日に何したの？」と聞いているよ！last Sundayは「先週の日曜日」だよ！"},
{q:"「He is watching TV now.」の過去形は？",c:["He was watching TV.","He watched TV.","He did watch TV.","He watches TV."],a:0,h:"be動詞をwasに変える",e:"現在進行形の過去→過去進行形：was/were + ing。",es:"「〜していた」という過去進行形は、isをwasに変えるだけだよ！"},
{q:"「I ate sushi for the first time.」の意味は？",c:["私は初めて寿司を食べました","私は寿司をよく食べます","私は寿司を食べています","私は寿司が好きです"],a:0,h:"for the first time=初めて",e:"for the first time=初めて。ate=eatの過去形。",es:"for the first timeは「初めて」という意味だよ！初体験を話すときに使うよ！"},
{q:"「speak」の過去形は？",c:["spoke","speaked","speak","spoken"],a:0,h:"不規則変化",e:"speak → spoke（不規則）",es:"speakも特別な変化をするよ！過去形はspokeになるんだよ！"},
{q:"「write」の過去形は？",c:["wrote","writed","write","written"],a:0,h:"不規則変化",e:"write → wrote（不規則）",es:"writeも特別な変化をするよ！書いたことを言うときはwroteを使うよ！"},
{q:"「buy」の過去形は？",c:["bought","buyed","buy","boughted"],a:0,h:"不規則変化",e:"buy → bought（不規則）",es:"buyも特別な変化をするよ！買ったことを言うときはboughtを使うよ！"},
{q:"「I bought a new bag yesterday.」の意味は？",c:["私は昨日新しいバッグを買いました","私は新しいバッグを買います","私は新しいバッグを持っています","私は昨日バッグを売りました"],a:0,h:"bought=buyの過去形",e:"bought=buy（買う）の過去形。yesterday=昨日。",es:"boughtはbuyの過去形だよ！昨日新しいバッグを買ったよ、という文だよ！"},
{q:"「think」の過去形は？",c:["thought","thinked","think","thanked"],a:0,h:"不規則変化",e:"think → thought（不規則）",es:"thinkも特別な変化をするよ！考えたことを言うときはthoughtを使うよ！"},
{q:"「We enjoyed the party.」の意味は？",c:["私たちはパーティーを楽しみました","私たちはパーティーを楽しんでいます","私たちはパーティーに行きます","私たちはパーティーが好きです"],a:0,h:"enjoyed=enjoyの過去形",e:"enjoy → enjoyed（規則変化）。We enjoyed the party.",es:"enjoyedはenjoyの過去形だよ！パーティーを楽しんだよ、という文だよ！"},
{q:"三人称単数現在のsとはどのような場合につける？",c:["主語がhe/she/it（三人称単数）で現在形のとき","主語がIのとき","主語がyouのとき","過去形のとき"],a:0,h:"三人称・単数・現在の3条件",e:"三人称（he/she/it）+単数+現在形→ 動詞にsまたはesをつける。",es:"he・she・itが主語のとき、動詞にsかesをつけるルールだよ！"}
]
};
